name: tf2.4
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2021.1.19=h06a4308_0
  - certifi=2020.12.5=py38h06a4308_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1i=h27cfd23_0
  - pip=20.3.3=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py38h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.11.0
    - astunparse==1.6.3
    - cachetools==4.2.1
    - chardet==4.0.0
    - cycler==0.10.0
    - decorator==4.4.2
    - dm-sonnet==2.0.0
    - dm-tree==0.1.5
    - flatbuffers==1.12
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - graph-nets==1.1.1.dev0
    - grpcio==1.32.0
    - h5py==2.10.0
    - idna==2.10
    - joblib==1.0.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.3
    - matplotlib==3.3.4
    - networkx==2.5
    - numpy==1.19.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - pandas==1.2.1
    - pillow==8.1.0
    - protobuf==3.14.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.5
    - pyyaml==5.4.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7
    - scikit-learn==0.24.1
    - scipy==1.6.0
    - six==1.15.0
    - sklearn==0.0
    - tabulate==0.8.7
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.4.1
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - tqdm==4.56.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.3
    - werkzeug==1.0.1
    - wrapt==1.12.1
prefix: /global/homes/x/xju/.conda/envs/tf2.4
