name: tf2
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - afterimage=1.21=h37b8349_1003
  - astroid=2.4.1=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - binutils-meta=1.0.4=0
  - binutils_impl_linux-64=2.33.1=he6710b0_7
  - binutils_linux-64=2.33.1=h9595d00_15
  - blas=1.0=mkl
  - bleach=3.1.4=py_0
  - bzip2=1.0.8=h7b6447c_0
  - c-compiler=1.0.4=h516909a_0
  - ca-certificates=2020.1.1=0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2020.4.5.1=py37_0
  - cffi=1.14.0=py37h2e261b9_0
  - cfitsio=3.470=hb7c8383_2
  - chardet=3.0.4=py37_1003
  - compilers=1.0.4=0
  - cryptography=2.9.2=py37h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cxx-compiler=1.0.4=hc9558a2_0
  - cycler=0.10.0=py37_0
  - davix=0.7.6=hb44b51d_0
  - dbus=1.13.14=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - fftw=3.3.8=h7b6447c_3
  - fontconfig=2.13.1=h86ecdb6_1001
  - fortran-compiler=1.0.4=he991be0_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - ftgl=2.4.0=hc56bac0_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_15
  - gdk-pixbuf=2.38.2=h3f25603_3
  - gettext=0.19.8.1=hd7bead4_3
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_15
  - giflib=5.2.1=h516909a_2
  - gl2ps=1.4.0=he06d7ca_0
  - glew=2.1.0=he1b5a44_0
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=h6c8ec71_1
  - gobject-introspection=1.56.1=py37hbc4ca2d_2
  - graphite2=1.3.13=h23475e2_0
  - graphviz=2.42.3=h0511662_0
  - gsl=2.6=h294904e_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_15
  - harfbuzz=2.4.0=h9f30f68_3
  - icu=64.2=he1b5a44_1
  - importlib_metadata=1.5.0=py37_0
  - intel-openmp=2020.1=217
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.13.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py37_0
  - jedi=0.17.0=py37_0
  - jinja2=2.11.2=py_0
  - jpeg=9c=h14c3975_1001
  - json5=0.9.4=py_0
  - jsonschema=3.2.0=py37_0
  - jupyter_client=6.1.3=py_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_core=4.6.3=py37_0
  - jupyter_nbextensions_configurator=0.4.1=py37_0
  - jupyterlab=1.2.6=py_0
  - jupyterlab_server=1.1.1=py_0
  - kiwisolver=1.2.0=py37hfd86e86_0
  - krb5=1.17.1=h173b8e3_0
  - lazy-object-proxy=1.4.3=py37h7b6447c_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=15_mkl
  - libcblas=3.8.0=15_mkl
  - libclang=9.0.1=default_hde54327_0
  - libcroco=0.6.13=h8d621e5_1
  - libcurl=7.69.1=h20c2e04_0
  - libcxx=10.0.0=hc9558a2_2
  - libcxxabi=10.0.0=2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libiconv=1.15=h63c8f33_5
  - libllvm9=9.0.1=he513fc3_1
  - libpng=1.6.37=hbc83047_0
  - librsvg=2.48.4=h33a7fed_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc7e4089_6
  - libtool=2.4.6=h7b6447c_5
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h1bed415_1
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - lz4-c=1.9.2=he6710b0_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1=py37h30547a4_0
  - mccabe=0.6.1=py37_1
  - metakernel=0.23.0=py37_0
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.6=py_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.4=py_0
  - ninja=1.9.0=py37hfd86e86_0
  - nodejs=10.13.0=he6710b0_0
  - notebook=6.0.3=py37_0
  - nspr=4.22=he6710b0_0
  - nss=3.46.1=hab99668_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h7b6447c_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - pango=1.42.4=ha030887_1
  - parso=0.7.0=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=7.1.2=py37hb39fc2d_0
  - pip=20.0.2=py37_3
  - pixman=0.38.0=h7b6447c_0
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pylint=2.5.2=py37_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.12.3=py37h8685d9f_3
  - pyrsistent=0.16.0=py37h7b6447c_0
  - pysocks=1.7.1=py37_0
  - pythia8=8.244=py37h3340039_0
  - python=3.7.6=h8356626_5_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.5.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pyzmq=18.1.1=py37he6710b0_0
  - qt=5.12.5=hd8c4c69_1
  - readline=8.0=h7b6447c_0
  - root=6.20.4=py37hb606994_3
  - root-binaries=6.20.4=py37hb606994_3
  - root-dependencies=6.20.4=py37hb606994_3
  - root_base=6.20.4=py37hdeb96f3_3
  - scipy=1.4.1=py37h0b6359f_0
  - send2trash=1.5.0=py37_0
  - setuptools=46.4.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tbb=2020.1=hc9558a2_0
  - tbb-devel=2020.1=hc9558a2_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hed695b0_0
  - toml=0.10.0=py37h28b3542_0
  - torchvision=0.6.0=py37_cu101
  - tornado=6.0.4=py37h7b6447c_1
  - traitlets=4.3.3=py37_0
  - typed-ast=1.4.1=py37h7b6447c_0
  - urllib3=1.25.8=py37_0
  - vdt=0.4.3=he1b5a44_0
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.34.2=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.11.2=py37h7b6447c_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxcursor=1.2.0=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxft=2.3.3=h71203ad_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xrootd=4.11.3=py37h90e4dd4_2
  - xxhash=0.7.2=h516909a_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h0b5b093_3
  - pip:
    - absl-py==0.9.0
    - annoy==1.16.3
    - astor==0.8.1
    - astunparse==1.6.3
    - cachetools==4.0.0
    - cloudpickle==1.3.0
    - contextlib2==0.6.0.post1
    - dm-sonnet==2.0.0b0
    - dm-tree==0.1.2
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.11.2
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - graph-nets==1.1.1.dev0
    - grpcio==1.27.2
    - h5py==2.10.0
    - idna==2.8
    - joblib==0.14.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.2.1
    - more-itertools==8.2.0
    - mpi4py==3.0.0
    - numexpr==2.7.1
    - numpy==1.18.1
    - oauthlib==3.1.0
    - opt-einsum==3.1.0
    - pandas==1.0.1
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - pytz==2019.3
    - pyyaml==5.3
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scikit-learn==0.22.2.post1
    - semantic-version==2.8.4
    - sklearn==0.0
    - tables==3.6.1
    - tensorboard==2.2.1
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorflow==2.2.0
    - tensorflow-estimator==2.2.0
    - tensorflow-probability==0.9.0
    - termcolor==1.1.0
    - trackml==3
    - werkzeug==1.0.0
prefix: /global/homes/x/xju/.conda/envs/tf2

