tfrec_dir_train: /global/homes/x/xju/work/TopReco/tthyy/inputs/train/*
tfrec_dir_val: /global/homes/x/xju/work/TopReco/tthyy/inputs/val/*
output_dir:  /global/homes/x/xju/work/TopReco/tthyy/trained
prod_name: test4
model_name: FourTopPredictor # don't change!
parameters:
    batch_size: 500
    learning_rate: 0.001
    epochs: 100
    earlystop_metric: "auc_te" #auc_te, acc_te, pre_te, rec_te
    acceptable_failure: 5
    num_iters: 8
    shuffle_buffer_size: 2