tfrec_dir_train: /global/homes/x/xju/work/TopTagger/tfrec/*_*.tfrec
tfrec_dir_val: /global/homes/x/xju/work/TopTagger/tfrec_val/*_*.tfrec
output_dir: /global/homes/x/xju/work/TopTagger/trained
prod_name: noedge_fullevts
model_name: GlobalClassifierNoEdgeInfo
parameters:
    batch_size: 50
    n_iters: 10
    learning_rate: 0.0005
    real_weight: 1.
    fake_weight: 1.
    epochs: 20
    earlystop_metric: "auc_te" # acc_te, pre_te, rec_te
    acceptable_failure: 2